"use client";

import { motion } from "framer-motion";
import {
  IoCheckmarkCircleOutline,
  IoCloseCircleOutline,
} from "react-icons/io5";

const comparisons = [
  {
    before: "Track applications in a messy spreadsheet",
    after: "Visual Kanban board with drag-and-drop status",
  },
  {
    before: "Manually compare job requirements to your resume",
    after: "AI scores every role and explains the match",
  },
  {
    before: "Google generic interview questions",
    after: "Role-specific questions generated by AI",
  },
  {
    before: "Copy-paste cover letter templates",
    after: "Tailored letters with configurable tone",
  },
  {
    before: "Forget which recruiter you followed up with",
    after: "Stage reminders when things go quiet",
  },
];

export default function BeforeAfter() {
  return (
    <section
      className="px-6 py-20 border-t"
      style={{ borderColor: "var(--cp-border-soft)" }}
    >
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-14">
          <p
            className="font-mono-label text-xs uppercase"
            style={{ color: "var(--cp-accent)" }}
          >
            Why switch
          </p>
          <h2 className="font-display text-3xl md:text-4xl font-semibold mt-3">
            Spreadsheets vs CareerPilot.
          </h2>
        </div>

        <div
          className="rounded-2xl overflow-hidden"
          style={{
            background: "var(--cp-surface)",
            border: "1px solid var(--cp-border)",
          }}
        >
          <div className="grid grid-cols-2">
            <div
              className="px-6 py-4 font-mono-label text-xs uppercase text-center"
              style={{
                background: "var(--cp-bg)",
                borderBottom: "1px solid var(--cp-border)",
                borderRight: "1px solid var(--cp-border)",
                color: "var(--cp-text-faint)",
              }}
            >
              Before
            </div>
            <div
              className="px-6 py-4 font-mono-label text-xs uppercase text-center"
              style={{
                background: "var(--cp-bg)",
                borderBottom: "1px solid var(--cp-border)",
                color: "var(--cp-accent)",
              }}
            >
              After
            </div>
          </div>

          {comparisons.map((row, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -10 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08 }}
              className="grid grid-cols-2"
              style={{
                borderBottom:
                  i < comparisons.length - 1 ? "1px solid var(--cp-border)" : "none",
              }}
            >
              <div
                className="flex items-start gap-3 px-6 py-4"
                style={{ borderRight: "1px solid var(--cp-border)" }}
              >
                <IoCloseCircleOutline
                  size={18}
                  className="mt-0.5 shrink-0"
                  style={{ color: "#ef4444" }}
                />
                <span
                  className="text-sm"
                  style={{ color: "var(--cp-text-muted)" }}
                >
                  {row.before}
                </span>
              </div>
              <div className="flex items-start gap-3 px-6 py-4">
                <IoCheckmarkCircleOutline
                  size={18}
                  className="mt-0.5 shrink-0"
                  style={{ color: "var(--cp-accent)" }}
                />
                <span className="text-sm">{row.after}</span>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
